# Generated by Django 3.2.22 on 2023-11-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protectphoto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='processed_images/')),
                ('processed_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
